//! Timecode regression against **real vinyl**, not a synthetic carrier.
//!
//! Every other timecode test in this workspace feeds the decoder a
//! carrier generated by `dub_timecode::signal::Generator` — a clean
//! sine pair with white noise if we ask for it. Real vinyl is not that.
//! It has surface noise with lag-1 autocorrelation around 0.8, dust
//! ticks, wow and flutter, cartridge channel imbalance, and a hand on
//! the platter.
//!
//! That difference has already cost a rig session. `LESSONS.md` records
//! it: the lag-1 phase-difference estimator *shrinks* under correlated
//! noise, and coherence of 0.999 still read **−0.31 % pitch at a true
//! zero** on a real deck. A synthetic test cannot produce that bias,
//! because synthetic noise is white by construction. The fixtures here
//! can, and `steady_nominal_has_no_pitch_bias` is the test that would
//! have caught it in CI instead of on stage.
//!
//! The fixtures are 10 s excerpts of `dub capture` recordings from the
//! SL 3, stored as 24-bit FLAC (verified bit-exact off the original
//! 32-bit float — the captures sit exactly on the 24-bit grid because
//! `dub capture` applies no gain). See `testdata/timecode/README.md` for
//! what each one contains and where it came from.
//!
//! These drive the **production** path — `TimecodeInput::drive`, so the
//! decoder, the rate smoother, anchor learning and the lift policy, in
//! 512-frame quanta with the engine's own calibration trigger. Not a
//! re-implementation that can drift from it.

#![cfg(test)]
#![allow(clippy::cast_precision_loss)] // counts and sample rates, all far under 2^23

use std::path::PathBuf;

use ringbuf::traits::{Producer as _, Split as _};

use crate::timecode::{TimecodeInput, TimecodeInputConfig};

/// The render quantum the engine actually gets from CoreAudio.
const QUANTUM: usize = 512;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/timecode")
        .join(name)
}

/// One quantum's worth of what the production path decided.
struct Quantum {
    rate: f64,
    confidence: f32,
    amplitude: f32,
    position_secs: f64,
    engaged: bool,
}

/// Replay a fixture through the real drive path.
fn replay(name: &str) -> Vec<Quantum> {
    let path = fixture(name);
    let track = dub_io::Track::load_from_path(&path)
        .unwrap_or_else(|e| panic!("load {}: {e}", path.display()));
    assert_eq!(track.channels(), 2, "timecode fixtures are stereo");
    let sr = track.sample_rate() as f32;
    let samples = track.samples();

    let rb = ringbuf::HeapRb::<f32>::new(track.sample_rate() as usize * 2);
    let (mut tx, rx) = rb.split();
    let cfg = TimecodeInputConfig {
        input_sample_rate: sr,
        ..TimecodeInputConfig::default()
    };
    let mut input = TimecodeInput::new(rx, cfg);

    let mut out = Vec::new();
    let mut calibrated = false;
    for quantum in samples.chunks(QUANTUM * 2) {
        assert_eq!(tx.push_slice(quantum), quantum.len());
        let _ = input.drive();
        let Some(o) = input.last_output() else {
            continue;
        };
        // Mirror the engine's auto-calibration trigger.
        if !calibrated && o.confidence > 0.8 && o.amplitude > 0.05 {
            input.begin_calibration(48_000);
            calibrated = true;
        }
        out.push(Quantum {
            rate: o.rate,
            confidence: o.confidence,
            amplitude: o.amplitude,
            position_secs: o.position_secs,
            engaged: input.policy().is_engaged(),
        });
    }
    assert!(out.len() > 100, "{name}: only {} quanta decoded", out.len());
    out
}

/// **The lag-1 bias regression.** A platter running at nominal on a
/// real record must decode to a rate of 1.0.
///
/// Measured on this fixture the mean sits at 0.9997 — a −0.034 % bias,
/// which is the residual the long-lag estimator leaves. The tolerance
/// is 0.15 %, chosen to sit well clear of that while catching the
/// −0.31 % the lag-1 estimator produced before it was replaced. A
/// synthetic carrier reads a clean 1.0 either way, which is exactly why
/// this needs real groove noise.
#[test]
fn steady_nominal_has_no_pitch_bias() {
    let q = replay("serato-cv02-steady-nominal.flac");
    let locked: Vec<&Quantum> = q.iter().filter(|x| x.confidence > 0.9).collect();
    assert!(
        locked.len() * 100 / q.len() >= 95,
        "expected a near-solid lock on a steady nominal platter, got {}/{}",
        locked.len(),
        q.len()
    );

    let mean = locked.iter().map(|x| x.rate).sum::<f64>() / locked.len() as f64;
    let bias_pct = (mean - 1.0) * 100.0;
    assert!(
        bias_pct.abs() < 0.15,
        "pitch bias {bias_pct:+.3} % at a true nominal — the lag-1 correlated-noise \
         shrink read −0.31 % here before the long-lag estimator replaced it (LESSONS)"
    );
}

/// The groove position must advance at real time, and monotonically.
///
/// This is the relative integrator measured against the clock rather
/// than against itself: 10 s of nominal groove is 10 s of playhead.
#[test]
fn steady_nominal_position_advances_at_real_time() {
    let q = replay("serato-cv02-steady-nominal.flac");
    let locked: Vec<&Quantum> = q.iter().filter(|x| x.confidence > 0.9).collect();

    let span_secs = (locked.len() * QUANTUM) as f64 / 48_000.0;
    let travelled = locked.last().unwrap().position_secs - locked.first().unwrap().position_secs;
    let err_pct = (travelled - span_secs) / span_secs * 100.0;
    assert!(
        err_pct.abs() < 0.5,
        "groove travelled {travelled:.3} s over {span_secs:.3} s of audio ({err_pct:+.2} %)"
    );

    // No teleports: a real groove cannot jump. One quantum at 1x is
    // ~10.7 ms, so anything past 50 ms is a decode fault, not motion.
    for w in locked.windows(2) {
        let step = w[1].position_secs - w[0].position_secs;
        assert!(
            step.abs() < 0.050,
            "position jumped {:.1} ms in one quantum",
            step * 1000.0
        );
    }
}

/// A hand on the platter must not shake the policy loose.
///
/// This fixture is ten seconds of real scratching — the decoded rate
/// spans −1.32 to +1.30. The lift policy exists to tell "the needle
/// left the groove" from "the DJ is working the record", and getting
/// that wrong burst-plays a track with the needle up. Three SL 3
/// iterations went into it (LESSONS); nothing tested it against an
/// actual hand until now.
#[test]
fn scratching_never_reads_as_a_lift() {
    let q = replay("serato-cv02-scratch.flac");

    let reverse = q.iter().filter(|x| x.rate < -0.5).count();
    let forward = q.iter().filter(|x| x.rate > 0.5).count();
    assert!(
        reverse > 20 && forward > 20,
        "fixture should contain real back-and-forth motion: {reverse} reverse, {forward} forward"
    );

    // Once engaged, the policy should stay engaged: the carrier is
    // present throughout, only its direction and speed change.
    let first_engaged = q.iter().position(|x| x.engaged).expect("never engaged");
    let dropouts = q[first_engaged..].iter().filter(|x| !x.engaged).count();
    let tail = q.len() - first_engaged;
    assert!(
        dropouts * 100 / tail < 10,
        "policy disengaged in {dropouts}/{tail} quanta while the needle was in the groove"
    );
}

/// The needle drop must not burst-play before the carrier is real.
///
/// "In Timecode mode, never auto-play on load" is a LESSONS rule with a
/// bug behind it. The first seconds of this fixture are the stylus
/// landing: amplitude climbing out of nothing, confidence following.
/// The policy must not engage while there is no carrier to engage on.
#[test]
fn the_needle_drop_does_not_engage_early() {
    let q = replay("serato-cv02-needle-drop.flac");

    let silent: Vec<&Quantum> = q.iter().take_while(|x| x.amplitude < 0.01).collect();
    assert!(
        silent.len() > 5,
        "fixture should open before the stylus lands, got {} quiet quanta",
        silent.len()
    );
    assert!(
        silent.iter().all(|x| !x.engaged),
        "policy engaged with no carrier — this is the burst-play-with-the-needle-up bug"
    );

    // And it must get there in the end.
    assert!(
        q.iter().any(|x| x.engaged),
        "policy never engaged after the needle landed"
    );
}
