//! Platform-correct on-disk locations for the Dub library and its
//! caches. Centralised here so M11a is the one place that knows
//! where `library.sqlite` lives; the rest of the crate takes a path.
//!
//! Reference: `docs/LIBRARY-SCHEMA.md` § "File system locations".

use std::path::PathBuf;

use crate::error::{LibraryError, Result};

/// Subdirectory under `~/Library/Application Support/` where the
/// Dub library database lives. Mirrors the bundle identifier
/// convention without depending on it (the CLI doesn't have an
/// `Info.plist`).
const APP_SUPPORT_SUBDIR: &str = "Dub";

/// File name of the SQLite database inside `APP_SUPPORT_SUBDIR`.
const LIBRARY_DB_FILE: &str = "library.sqlite";

/// Subdirectory under `~/Library/Caches/Dub/` for waveform sidecars
/// generated by the M10.5j cache. The key migrates from
/// path-hash to canonical fingerprint at M11a per
/// `docs/LIBRARY-SCHEMA.md` § "File system locations" — concretely,
/// files are now named `{fingerprint_hex}.wf` under this directory.
const WAVEFORMS_CACHE_SUBDIR: &str = "waveforms";

/// The default on-disk path to `library.sqlite`. Creates the parent
/// directory chain if needed; the caller of [`crate::Library::open_default`]
/// expects an openable path.
///
/// On macOS this resolves to
/// `~/Library/Application Support/Dub/library.sqlite`.
pub fn default_library_db_path() -> Result<PathBuf> {
    let base = dirs::config_dir().ok_or_else(|| LibraryError::VolumeUuidUnavailable {
        path: PathBuf::from("<config_dir>"),
        reason: "platform did not expose a user config directory",
    })?;
    let dir = base.join(APP_SUPPORT_SUBDIR);
    ensure_dir(&dir)?;
    Ok(dir.join(LIBRARY_DB_FILE))
}

/// The default on-disk directory holding waveform sidecars. The
/// renderer + M10.5j cache use this path; the library subsystem
/// stores filenames relative to it in `analysis_cache.waveform_sidecar_path`.
///
/// On macOS this resolves to `~/Library/Caches/Dub/waveforms/`.
pub fn default_waveforms_cache_dir() -> Result<PathBuf> {
    let base = dirs::cache_dir().ok_or_else(|| LibraryError::VolumeUuidUnavailable {
        path: PathBuf::from("<cache_dir>"),
        reason: "platform did not expose a user cache directory",
    })?;
    let dir = base.join(APP_SUPPORT_SUBDIR).join(WAVEFORMS_CACHE_SUBDIR);
    ensure_dir(&dir)?;
    Ok(dir)
}

/// Ensures the given directory and its parents exist, surfacing any
/// I/O error with the offending path.
fn ensure_dir(dir: &std::path::Path) -> Result<()> {
    std::fs::create_dir_all(dir).map_err(|e| LibraryError::io(dir, e))?;
    Ok(())
}
